/* ext4fs
 * Copyright 2025 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software granted the above
 * copyright notice and this permission paragraph are included in all
 * copies and substantial portions of this software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */
#include <stdio.h>
#include <stdint.h>

#define CRC32C_POLYNOMIAL          0x1EDC6F41U
#define CRC32C_POLYNOMIAL_REVERSED 0x82F63B78U

int main (void) {
  uint32_t crc;
  uint32_t i;
  uint8_t j;
  printf("/* generated by crc32c_table */\n"
         "static const uint32_t crc32c_table[256] = {\n");
  i = 0;
  while (i < 256) {
    crc = i;
    j = 0;
    while (j < 8) {
      crc = (crc >> 1) ^ (CRC32C_POLYNOMIAL_REVERSED &
                          -(int)(crc & 1));
      j++;
    }
    printf("0x%08X,%s", crc, (i % 4 == 3) ? "\n" : " ");
    i++;
  }

  printf("};\n");
  return 0;
}
